name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-15 # arm64
    steps:
      - uses: actions/checkout@v7
      - name: Install build deps
        run: brew install pkgconf openssl@3
      - name: Build and verify
        run: ./build.sh
      - uses: actions/upload-artifact@v7
        with:
          name: openvpn-aws
          path: dist/
          retention-days: 7
